# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d67c8c0718e024219919b72b358228bf1327f923e46671911c7004af04b32dea558f5fc70e22acf73755986519139c43232ad83d1d5d4b474cac85d7d190963

test:
  secret_key_base: 969895ed88717514d150e9f5a63d22a9bb68f1cd173effcddb1beaca4f7d412bcaa6de66865e7205429f9af1a6b1471e9a86e963445549a225d085e7e188b38a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
